#!/usr/bin/env python3
"""Execute action code from a file and record video + joint state data.

Reads a Python action-code script (e.g. generated by the waypoint editor),
runs it in the same CodeExecutionEnvBase harness used by handover_step.py,
and saves per-camera videos and per-arm joint-state .npz files.

Usage:
  python test_scripts/run_action_code.py action_code.py
  python test_scripts/run_action_code.py action_code.py --output_dir dataset/my_run
  python test_scripts/run_action_code.py action_code.py --yellow_offset -0.28,0.065,0.0

The action code file should contain bare Python that uses the same API
functions available in the editor / handover_step (goto_pose_arm0,
open_gripper_arm1, get_object_pose, etc.).
"""

import argparse
import os
import sys
from datetime import datetime

import imageio
import numpy as np
import robosuite.macros as macros

macros.IMAGE_CONVENTION = "opencv"

os.environ["PATH"] = "/usr/local/cuda-12.9/bin:" + os.environ.get("PATH", "")
os.environ["LD_LIBRARY_PATH"] = (
    "/usr/local/cuda-12.9/lib64:" + os.environ.get("LD_LIBRARY_PATH", "")
)
os.environ["XLA_FLAGS"] = "--xla_gpu_cuda_data_dir=/usr/local/cuda-12.9"

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)

from robosuite.environments.custom.franka_robosuite_tape_handover import (
    FrankaRobosuiteTapeHandover,
)
from robosuite.environments.custom.control.base_executor import (
    CodeExecutionEnvBase,
    CodeExecEnvConfig,
)
from api.franka_priviledged_api import FrankaControlTapeHandoverPrivilegedApi
from api.base_api import register_api


def parse_offset_list(offset_str):
    try:
        values = [float(x.strip()) for x in offset_str.split(",")]
        if len(values) != 3:
            raise ValueError("Offset must contain exactly 3 values (x, y, z)")
        return np.array(values, dtype=float)
    except ValueError as e:
        raise argparse.ArgumentTypeError(
            f"Invalid offset format '{offset_str}': {e}. "
            "Expected format: 'x,y,z' (e.g., '0.0,-0.7,0.0')"
        )


def save_videos(dataset_dir, base_filename, all_video_frames, fps=20):
    """Save per-camera videos from collected frame buffers."""
    if not all_video_frames:
        print("No video frames were captured.")
        return

    for cam_name, frames in all_video_frames.items():
        if not frames:
            continue
        suffix = {
            "agentview": "agentview",
            "robot0_eye_in_hand": "robot0_wrist",
            "robot1_eye_in_hand": "robot1_wrist",
        }.get(cam_name, cam_name)
        path = os.path.join(dataset_dir, f"{base_filename}_{suffix}.mp4")
        print(f"Saving {cam_name} video ({len(frames)} frames) to {path}...")
        imageio.mimsave(path, frames, fps=fps)


def save_joint_states(dataset_dir, base_filename, joint_states):
    """Save per-arm joint positions, velocities, and gripper states."""
    if not joint_states:
        print("No joint states were collected.")
        return

    for robot_idx in range(2):
        prefix = f"robot{robot_idx}"
        data = {}
        for key, out_key in [
            (f"{prefix}_joint_pos", "joint_positions"),
            (f"{prefix}_joint_vel", "joint_velocities"),
            (f"{prefix}_gripper_qpos", "gripper_positions"),
        ]:
            if key in joint_states[0]:
                data[out_key] = np.stack([s[key] for s in joint_states])
        if data:
            path = os.path.join(dataset_dir, f"{base_filename}_{prefix}_joints.npz")
            np.savez_compressed(path, **data)
            print(
                f"{prefix} joint states saved to {path} ({len(joint_states)} samples)"
            )


def main():
    parser = argparse.ArgumentParser(
        description="Run an action-code script and record video + joint data.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
Examples:
  python test_scripts/run_action_code.py my_trajectory.py
  python test_scripts/run_action_code.py my_trajectory.py --output_dir dataset/run1
  python test_scripts/run_action_code.py my_trajectory.py --viser
""",
    )
    parser.add_argument(
        "action_code_file",
        help="Path to a .py file containing the action code to execute.",
    )
    parser.add_argument(
        "--output_dir",
        default=None,
        help="Directory for output files. Auto-generated if omitted.",
    )
    parser.add_argument(
        "--yellow_offset",
        type=parse_offset_list,
        default="-0.28,0.065,0.0",
        help="Yellow tape offset x,y,z (default: -0.28,0.065,0.0)",
    )
    parser.add_argument(
        "--duct_offset",
        type=parse_offset_list,
        default="-0.1,-0.065,0.0",
        help="Duct tape offset x,y,z (default: -0.1,-0.065,0.0)",
    )
    parser.add_argument(
        "--joint_state_fps",
        type=float,
        default=30.0,
        help="Sampling rate for joint state and video capture (default: 30.0)",
    )
    parser.add_argument(
        "--video_fps",
        type=float,
        default=20.0,
        help="FPS for saved video files (default: 20.0)",
    )
    parser.add_argument(
        "--viser",
        action="store_true",
        help="Enable live viser visualization during execution.",
    )
    parser.add_argument(
        "--max_frames",
        type=int,
        default=1200,
        help="Max agentview frames before declaring failure (default: 1200 = ~60s at 20fps)",
    )
    args = parser.parse_args()

    # ---- Read action code ----
    code_path = os.path.abspath(args.action_code_file)
    if not os.path.isfile(code_path):
        print(f"ERROR: Action code file not found: {code_path}")
        sys.exit(1)
    with open(code_path) as f:
        action_code = f.read()
    print(f"Loaded action code from {code_path} ({len(action_code)} chars)")

    yellow_offset = np.array(args.yellow_offset, dtype=float)
    duct_offset = np.array(args.duct_offset, dtype=float)
    print(f"Yellow tape offset: {yellow_offset}")
    print(f"Duct tape offset:   {duct_offset}")

    # ---- Build environment ----
    register_api(
        "franka-handover-privileged",
        lambda env: FrankaControlTapeHandoverPrivilegedApi(env),
    )

    controller_cfg_path = os.path.join(
        root_dir,
        "robosuite", "environments", "custom", "configs", "panda_joint_ctrl_slow.json",
    )

    print("Initializing low-level environment...")
    low_level_env = FrankaRobosuiteTapeHandover(
        controller_cfg=controller_cfg_path,
        viser_debug=args.viser,
        privileged=True,
        enable_render=False,
        use_wrist_cameras=True,
        yellow_tape_offset=yellow_offset,
        duct_tape_offset=duct_offset,
    )

    cfg = CodeExecEnvConfig(
        low_level=low_level_env,
        apis=["franka-handover-privileged"],
        prompt="Execute user-provided action code.",
    )

    print("Initializing code execution environment...")
    exec_env = CodeExecutionEnvBase(cfg)
    print("Resetting environment...")
    exec_env.reset()

    # ---- Enable recording ----
    SIMULATION_FPS = 500.0
    joint_state_freq_steps = max(1, int(SIMULATION_FPS / args.joint_state_fps))
    effective_fps = SIMULATION_FPS / joint_state_freq_steps
    print(
        f"Recording video + joint state every {joint_state_freq_steps} sim steps "
        f"(~{effective_fps:.1f} Hz)..."
    )
    exec_env.enable_video_capture(True, freq=joint_state_freq_steps)
    low_level_env.enable_joint_state_collection(
        True, clear=True, freq=joint_state_freq_steps
    )

    # ---- Execute ----
    print(f"\nExecuting action code...")
    obs, reward, terminated, truncated, info = exec_env.step(action_code)

    # ---- Determine output directory ----
    if args.output_dir:
        dataset_dir = args.output_dir
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        script_name = os.path.splitext(os.path.basename(code_path))[0]
        yo, do = yellow_offset, duct_offset
        dir_name = (
            f"{script_name}"
            f"_yellow_{yo[0]}_{yo[1]}_{yo[2]}"
            f"_duct_{do[0]}_{do[1]}_{do[2]}"
            f"_{timestamp}"
        ).replace(".", "_").replace("-", "neg")
        dataset_dir = os.path.join("dataset", dir_name)

    os.makedirs(dataset_dir, exist_ok=True)
    print(f"Output directory: {dataset_dir}")

    # ---- Save action code alongside data ----
    code_save_path = os.path.join(dataset_dir, "action_code.py")
    with open(code_save_path, "w") as f:
        f.write(action_code)
    print(f"Action code saved to {code_save_path}")

    # ---- Save videos ----
    base_filename = "rollout"
    all_video_frames = low_level_env.get_camera_frames()
    save_videos(dataset_dir, base_filename, all_video_frames, fps=args.video_fps)

    # ---- Save joint states ----
    joint_states = low_level_env.get_collected_joint_states(clear=False)
    save_joint_states(dataset_dir, base_filename, joint_states)

    # ---- Results ----
    print("\n" + "=" * 40)
    print("EXECUTION RESULTS")
    print("=" * 40)
    print(f"Reward: {reward}")
    print(f"Terminated: {terminated}")
    print(f"Truncated: {truncated}")
    task_completed = info.get("task_completed", False)
    print(f"Task Completed: {task_completed}")

    num_frames = 0
    if all_video_frames and "agentview" in all_video_frames:
        num_frames = len(all_video_frames["agentview"])
    print(f"Agentview frames: {num_frames}")

    if num_frames > args.max_frames:
        print(
            f"\nFAILURE: Video length ({num_frames} frames) exceeds "
            f"maximum ({args.max_frames} frames)."
        )
        sys.exit(2)

    if info.get("sandbox_rc") != 0:
        print("\nFAILURE: Code execution failed with an exception.")
        if info["stderr"]:
            print("\n--- STDERR ---")
            print(info["stderr"])
        sys.exit(1)

    print("\n--- STDOUT ---")
    print(info["stdout"])
    if info["stderr"]:
        print("\n--- STDERR ---")
        print(info["stderr"])

    print("\nDone.")


if __name__ == "__main__":
    main()
